name: Check format

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**.h'
      - '**.c'
      - 'liblouis/liblouis/liblouis.h.in'
  pull_request:
    branches: [ master ]
    paths:
      - '**.h'
      - '**.c'
      - 'liblouis/liblouis/liblouis.h.in'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  check-format:
    name: Check the code formatting

    runs-on: ubuntu-22.04

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y clang-format-14
    - name: Autogen && configure
      run: |
        ./autogen.sh
        ./configure
    - name: Check format
      run: |
        make format-sources
        git diff-index --exit-code HEAD -- .
