name: Run sanitizer checks

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**.h'
      - '**.c'

  pull_request:
    branches: [ master ]
    paths:
      - '**.h'
      - '**.c'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with ${{ matrix.sanitizer }} sanitizer for ${{ matrix.ucs }}
    strategy:
      matrix:
        ucs: [ucs2, ucs4]
        sanitizer: [address, leak, undefined]
        include:
          - sanitizer: "address"
            options: "ASAN_OPTIONS=detect_leaks=0"
          - sanitizer: "leak"
            options: "LSAN_OPTIONS=fast_unwind_on_malloc=0"
          - sanitizer: "undefined"
            options: "UBSAN_OPTIONS=halt_on_error=1"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev
      - name: Autogen
        run: ./autogen.sh
      - name: Configure
        run: CFLAGS="-fsanitize=${{ matrix.sanitizer }} -g" ./configure
        if: matrix.ucs == 'ucs2'
      - name: Configure with ucs4
        run: CFLAGS="-fsanitize=${{ matrix.sanitizer }} -g" ./configure --enable-ucs4
        if: matrix.ucs == 'ucs4'
      - name: Make check
        run: ${{ matrix.options }} make check
      - name: Store the test suite log
        if: ${{ always() }} # store the test suite log even if the tests failed
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: test-suite-${{ matrix.ucs }}-${{ matrix.sanitizer }}.log
          path: tests/test-suite.log
